name: ci

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runs-on:
          - windows-latest
          - depot-ubuntu-24.04-arm
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Download Go modules
        run: go mod download

      - name: Test
        run: make test
        env:
          CLISTAT_IS_CONTAINERIZED: "no"

  test-race:
    strategy:
      matrix:
        runs-on:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Download Go modules
        run: go mod download

      - name: Test race
        run: make test-race
        env:
          CLISTAT_IS_CONTAINERIZED: "no"

  test-container:
    strategy:
      matrix:
        runtime:
          - runc
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      options: "--runtime=${{ matrix.runtime }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Test
        run: make test
        env:
          CLISTAT_IS_CONTAINERIZED: "yes"

  test-container-race:
    strategy:
      matrix:
        runtime:
          - runc
    runs-on: ubuntu-latest
    container:
      image: golang:1.23
      options: "--runtime=${{ matrix.runtime }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Test race
        run: make test-race
        env:
          CLISTAT_IS_CONTAINERIZED: "yes"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Format
        run: make -B fmt

      - name: Check for unstaged
        run: ./scripts/check_unstaged.sh