name: ci

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runs-on:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.22"

      - name: Download Go modules
        run: go mod download

      - name: Test
        run: make test
